on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install --without dev,docs

      - name: Run tests
        run: poetry run pytest
